// Generated by https://quicktype.io

export interface Users {
    firstName: string;
    lastName:  string;
    document:   number;
    email:      string;
    password: string;
}

export interface Sites {
    id: number;
    imageId: number;
    name:  string;
    address:   string;
}

export interface Travel {
    origin: string;
    destiny: string;
    cost: number;
    completed: number;
}